books/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('warehouse.urls')),
    path('admin/', admin.site.urls),
]

warehouse/urls.py
'''url'''
from django.urls import path
from . import views

app_name = "warehouse"

urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('list_of_books/', views.listpage, name="list"),
    path('add/', views.addpage, name="add"),
    path('import/', views.importpage, name="import"),
    path('list_of_books/results/', views.search, name='search'),
    path('added/', views.bookaddedpage, name="bookadded")
]

warehouse/models.py
'''models'''

from django.db import models
from warehouse import util

class Book(models.Model):
    """Model class for books"""

    title = models.CharField(max_length=150)
    authors = models.CharField(max_length=100)
    #we're assuming that no book is published before 0 A.D.
    publishedDate = models.IntegerField(null=True,
                                        validators=[util.not_negative])
    description = models.TextField()
    categories = models.CharField(max_length=200)

    def __str__(self):
        return self.title

warehouse/forms.py
'''forms'''
from django import forms
from .views import Book

class BookForm(forms.ModelForm):
    '''adding book'''
    title = forms.CharField(label='Tytuł', max_length=150)
    authors = forms.CharField(label='Autorzy', max_length=100)
    publishedDate = forms.IntegerField(label='Data publikacji')
    categories = forms.CharField(label='Kategoria', max_length=200)
    description = forms.CharField(label='Opis', max_length=500)
    class Meta:
        model = Book
        fields = '__all__'
        

warehouse/views.py
'''views'''

from django.db.models import Q
from django.shortcuts import render, redirect
from .models import Book
from .forms import BookForm


def homepage(request):
    '''rendering function'''
    return render(request=request,
                  template_name='warehouse/home.html',
                  context={'books': Book.objects.all()})

def listpage(request):
    '''rendering function'''
    return render(request=request,
                  template_name='warehouse/list.html',
                  context={'books': Book.objects.all()})

def addpage(request):
    '''rendering function'''
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/added/")
    form = BookForm
    return render(request=request,
                  template_name='warehouse/add.html',
                  context={'form':form})

def importpage(request):
    '''rendering function'''
    book = {}
    if 'key_word' in request.GET:
        key_word = request.GET['key_word']
        url = 'https://www.googleapis.com/books/v1/volumes?q=%s' % key_word
        response = request.get(url)
        book = response.json()
        book = book.get("items")
    return render(request,
                  template_name='warehouse/import.html',
                  context={'book': book})

def bookaddedpage(request):
    '''rendering function'''
    return render(request=request,
                  template_name='warehouse/bookadded.html',
                  context={'books': Book.objects.all()})

def search(request):
    '''search function'''
    template = 'warehouse/list.html'

    query = request.GET.get('q')

    if query:
        results = Book.objects.filter(Q(title__icontains=query) |
                                      Q(authors__icontains=query) |
                                      Q(categories__icontains=query))
    else:
        results = Book.objects.all()


    context = {'books':results}

    return render(request, template, context)

# class IndexView(generic.ListView):
#     template_name = 'warehouse/header.html'
#     page_template = 'warehouse/all_movies.html'
#     context_object_name = 'books'
#     model = Book

#     def get_context_data(self, **kwargs):
#         context = super(IndexView, self).get_context_data(**kwargs)
#         context.update({
#             'all_books': Book.objects.all(),
#             'page_title': 'Najnowsze'
#         })
#         return context

#     def get_queryset(self):
#         query = self.request.GET.get('q')
#         if query:
#             return Book.objects.filter(title__icontains=query)
#         else:
#             return Book.objects.all()

warehouse/templates/warehouse/add.html
{% extends "warehouse/header.html" %}

{% block content %}

<p><h5>Dodawanie książki</h5></p>

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
    
    <button class="btn waves-effect waves-light" type="submit" name="action">Dodaj do bazy
            <i class="material-icons right"></i>
    </button>
    </form>


{% endblock %}

warehouse/templates/warehouse/bookadded.html
{% extends "warehouse/header.html" %}

{% block content %}


<b>Książka została dodana! Sprawdź na liście :)</b>



{% endblock %}

warehouse/templates/warehouse/header.html
<head>
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>



<body>

<a href='/' class="waves-effect waves-light btn">Strona główna</a>
<a href='/list_of_books/' class="waves-effect waves-light btn">Lista książek</a>
<a href='/add/' class="waves-effect waves-light btn">Dodawanie książek</a>
<a href='/import/' class="waves-effect waves-light btn">Importowanie książek</a>

<br><br>

{% block content %}
{% endblock %}

</body>

warehouse/templates/warehouse/home.html
{% extends "warehouse/header.html" %}

{% block content %}

<h5>Witaj w Sanktuarium Wiedzy Tajemnej</h5>

{% endblock %}

warehouse/templates/warehouse/import.html
{% extends "warehouse/header.html" %}

{% block content %}

<p><h5>Importowanie z googleapis</h5></p>

  <form method="get">
    <input type="text" name="book">
    <button class="btn waves-effect waves-light", type="submit">Znajdź na googleapis</button>
  </form>
  {% if book %}
    <p>{{ book }}</p>
  {% endif %}

{% endblock %}

warehouse/templates/warehouse/list.html
{% extends "warehouse/header.html" %}

{% block content %}

<p><h5>Lista książek</h5></p>

    <form method="GET" action="{% url 'warehouse:search' %}" id="searchform">
        <input name="q" value="{{ request.GET.q }}" id="searchbox" type="text" placeholder="Search..."/>
        <button class="waves-effect waves-light btn-small" type='submit'>Szukaj</button>
    </form>

{% for boo in books %}
    <div><p>Tytuł: <b>{{boo.title}}</b></p>
    <p>Autorzy: {{boo.authors}}</p>
    <p>Rok wydania: {{boo.publishedDate}}</p>
    <p>Kategoria: {{boo.categories}}</p>
    <p>Opis: {{boo.desciption}}</p></div>

    <br><br>
{% endfor %}

{% endblock %}